"""FIFA U-17 World Cup 2015 cohort - retrospective demo data for the MPI.

Derived from public tournament rosters (Wikipedia) and the machina-market-radar
backtest (2026-08-03). Contains NO third-party market values - outcomes are
exposed only as a derived boolean (reached_eur5m_peak). 250 players with a
verified 11-year outcome window, out of the 414-player cohort.
"""

COHORT_ID = "fifa-u17-wc-2015"

PLAYERS = [
 {
  "name": "Felix Passlack",
  "country": "GER",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Borussia Dortmund",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "scored_and_market_aware",
  "p_reach": 0.5,
  "fact_points": 80,
  "projection_points": 1000,
  "mpi": 8580,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Pervis Estupiñán",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "LDU Quito",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "scored_and_market_aware",
  "p_reach": 0.5,
  "fact_points": 80,
  "projection_points": 1000,
  "mpi": 8580,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Anas Al-Aji",
  "country": "PAR",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Al-Wahda",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "scored_and_market_aware",
  "p_reach": 0.5,
  "fact_points": 40,
  "projection_points": 1000,
  "mpi": 8540,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Christian Pulisic",
  "country": "USA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Borussia Dortmund",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "scored_and_market_aware",
  "p_reach": 0.5,
  "fact_points": 40,
  "projection_points": 1000,
  "mpi": 8540,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Josip Brekalo",
  "country": "CRO",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Dinamo Zagreb",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "scored_and_market_aware",
  "p_reach": 0.5,
  "fact_points": 40,
  "projection_points": 1000,
  "mpi": 8540,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Kevin Masís",
  "country": "CRC",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Santos de Guápiles",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "scored_and_market_aware",
  "p_reach": 0.5,
  "fact_points": 40,
  "projection_points": 1000,
  "mpi": 8540,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Kelechi Nwakali",
  "country": "NGA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Diamond Academy",
  "goals_u17wc_2015": 5,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 200,
  "projection_points": 500,
  "mpi": 8200,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Victor Osimhen",
  "country": "NGA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Ultimate Strikers Academy",
  "goals_u17wc_2015": 9,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 200,
  "projection_points": 500,
  "mpi": 8200,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Amadou Haidara",
  "country": "MLI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Guidars FC",
  "goals_u17wc_2015": 3,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 120,
  "projection_points": 500,
  "mpi": 8120,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Dante Rigo",
  "country": "BEL",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "PSV Eindhoven",
  "goals_u17wc_2015": 3,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 120,
  "projection_points": 500,
  "mpi": 8120,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Jhon Pereira",
  "country": "ECU",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Norte América",
  "goals_u17wc_2015": 3,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 120,
  "projection_points": 500,
  "mpi": 8120,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Jorn Vancamp",
  "country": "BEL",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Anderlecht",
  "goals_u17wc_2015": 3,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 120,
  "projection_points": 500,
  "mpi": 8120,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Nikola Moro",
  "country": "CRO",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Dinamo Zagreb",
  "goals_u17wc_2015": 3,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 120,
  "projection_points": 500,
  "mpi": 8120,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Aly Mallé",
  "country": "MLI",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Black Star FC",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 80,
  "projection_points": 500,
  "mpi": 8080,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Brandon Vazquez",
  "country": "USA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Tijuana",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 80,
  "projection_points": 500,
  "mpi": 8080,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Julio Villalba",
  "country": "PAR",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Cerro Porteño",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 80,
  "projection_points": 500,
  "mpi": 8080,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Karlo Majić",
  "country": "CRO",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Dinamo Zagreb",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 80,
  "projection_points": 500,
  "mpi": 8080,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Kingsley Michael",
  "country": "NGA",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Abuja",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 80,
  "projection_points": 500,
  "mpi": 8080,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Marcelo Allende",
  "country": "CHI",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Cobreloa",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 80,
  "projection_points": 500,
  "mpi": 8080,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Vitaly Janelt",
  "country": "GER",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "RB Leipzig",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 80,
  "projection_points": 500,
  "mpi": 8080,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Yeison Guerrero",
  "country": "ECU",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Independiente del Valle",
  "goals_u17wc_2015": 2,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 80,
  "projection_points": 500,
  "mpi": 8080,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Abdoul Karim Danté",
  "country": "MLI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Jeanne d'Arc FC",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Brian Leiva",
  "country": "CHI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Universidad Católica",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Camilo Moya",
  "country": "CHI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Universidad de Chile",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Dante Vanzeir",
  "country": "BEL",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Genk",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Dennis Van Vaerenbergh",
  "country": "BEL",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Club Brugge",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Diego Mesén",
  "country": "CRC",
  "position": "DF",
  "birth_year": 1999,
  "club_2015": "Alajuelense",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Funsho Bamgboye",
  "country": "NGA",
  "position": "FW",
  "birth_year": 1999,
  "club_2015": "Aspire Academy",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Hunter Ashworth",
  "country": "NZL",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "University of San Francisco",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Joan Cortez",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Norte América",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Khanyisa Mayo",
  "country": "RSA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "SuperSport United",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Lucas Imrie",
  "country": "NZL",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Central United",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luka Ivanušec",
  "country": "CRO",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Lokomotiva",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Marcelino Ñamandú",
  "country": "PAR",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Rubio Ñu",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Morlaye Sylla",
  "country": "GUI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Espoirs Tanene",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Samuel Chukwueze",
  "country": "NGA",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Diamond Academy",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Sebastián Ferreira",
  "country": "PAR",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Sol de América",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Sékou Koïta",
  "country": "MLI",
  "position": "FW",
  "birth_year": 1999,
  "club_2015": "USC Kita",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Thendo Mukumela",
  "country": "RSA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Mamelodi Sundowns",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Tomás Conechny",
  "country": "ARG",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "San Lorenzo",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Washington Corozo",
  "country": "ECU",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Independiente del Valle",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Yerko Leiva",
  "country": "CHI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Universidad de Chile",
  "goals_u17wc_2015": 1,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "scored_not_market_aware",
  "p_reach": 0.25,
  "fact_points": 40,
  "projection_points": 500,
  "mpi": 8040,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Aleksandr Maksimenko",
  "country": "RUS",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Spartak Moscow",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Alhassane Soumah",
  "country": "GUI",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Aspire Academy",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Amir Gavrilov",
  "country": "RUS",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Rubin Kazan",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Anderson Naula",
  "country": "ECU",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "LDU Loja",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Andy Reyes",
  "country": "CRC",
  "position": "FW",
  "birth_year": 1999,
  "club_2015": "Carmelita",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Arthur",
  "country": "BRA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Santos",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Blás Riveros",
  "country": "PAR",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Olimpia",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Boris Tsygankov",
  "country": "RUS",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Spartak Moscow",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Borna Sosa",
  "country": "CRO",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Dinamo Zagreb",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Danil Krugovoy",
  "country": "RUS",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Zenit Saint Petersburg",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Denis Adamov",
  "country": "RUS",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Krasnodar",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Dino Halilović",
  "country": "CRO",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Udinese",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Dodô",
  "country": "BRA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Coritiba",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Dylan Stoffels",
  "country": "RSA",
  "position": "FW",
  "birth_year": 1999,
  "club_2015": "AmaZulu",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Erdinc Karakas",
  "country": "GER",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "VfL Bochum",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Eron",
  "country": "BRA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Vitória",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Evander",
  "country": "BRA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Vasco da Gama",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Exequiel Palacios",
  "country": "ARG",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "River Plate",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Federico Bonansea",
  "country": "ARG",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Belgrano",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Gabriel Ortiz",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Olimpia",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Gonzalo Jara",
  "country": "CHI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Universidad Católica",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Gökhan Gül",
  "country": "GER",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "VfL Bochum",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Görkem Sağlam",
  "country": "GER",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "VfL Bochum",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ian Smith",
  "country": "CRC",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Santos de Guápiles",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ismail Azzaoui",
  "country": "BEL",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "VfL Wolfsburg",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ismaël Traoré",
  "country": "MLI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Centre Salif Keita",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ivan Galanin",
  "country": "RUS",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Lokomotiv Moscow",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ivan Zirikov",
  "country": "RUS",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Dynamo Moscow",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Jack-Henry Sinclair",
  "country": "NZL",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "North Shore United",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "James McGarry",
  "country": "NZL",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Wellington United",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Javier Camareno",
  "country": "CRC",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Municipal Liberia",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Jens Teunckens",
  "country": "BEL",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Club Brugge",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Joe Bell",
  "country": "NZL",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Miramar Rangers",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Keanu Cupido",
  "country": "RSA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Diambars Academy",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Kléber",
  "country": "BRA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Flamengo",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Kobamelo Kodisang",
  "country": "RSA",
  "position": "FW",
  "birth_year": 1999,
  "club_2015": "Platinum Stars",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Lennerd Daneels",
  "country": "BEL",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "PSV Eindhoven",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Logan Rogerson",
  "country": "NZL",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Wellington United",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luis Hernández",
  "country": "CRC",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Saprissa",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Marcos Peano",
  "country": "ARG",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Unión de Santa Fe",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Markus Schubert",
  "country": "GER",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Dynamo Dresden",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Martin Erlić",
  "country": "CRO",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Sassuolo",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Matheusinho",
  "country": "BRA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "América-MG",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Niklas Dorsch",
  "country": "GER",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Bayern Munich",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Pablo Arboine",
  "country": "CRC",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Santos de Guápiles",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Pablo Ruíz",
  "country": "ARG",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "San Lorenzo",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Pavel Lelyukhin",
  "country": "RUS",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Spartak Moscow",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "René Meléndez",
  "country": "CHI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Audax Italiano",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Sarpreet Singh",
  "country": "NZL",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Wellington United",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Tyler Adams",
  "country": "USA",
  "position": "DF",
  "birth_year": 1999,
  "club_2015": "New York Red Bulls II",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Walter Ponce",
  "country": "CHI",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Palestino",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Yostin Salinas",
  "country": "CRC",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Limón",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Zacarías López",
  "country": "CHI",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "San Marcos",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Óscar Rodas",
  "country": "PAR",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Olimpia",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": True,
  "segment": "market_aware_only",
  "p_reach": 0.22,
  "fact_points": 0,
  "projection_points": 440,
  "mpi": 7940,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Aarón Murillo",
  "country": "CRC",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Alajuelense",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Abdulhadi Shalha",
  "country": "PAR",
  "position": "FW",
  "birth_year": 1999,
  "club_2015": "Al-Wahda",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Adrian Šemper",
  "country": "CRO",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Dinamo Zagreb",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ahmad Al-Khassi",
  "country": "PAR",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Al-Jaish",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Alan Franco",
  "country": "ECU",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Independiente del Valle",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Alejandro Barrientos",
  "country": "CRC",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Saprissa",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Alexis Velela",
  "country": "USA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "San Diego Surf",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Alper Ademoğlu",
  "country": "BEL",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Anderlecht",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Alseny Soumah",
  "country": "GUI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "FC Attouga",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Andrey",
  "country": "BRA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Vasco da Gama",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Athenkosi Dlala",
  "country": "RSA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "SuperSport United",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Auston Trusty",
  "country": "USA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Philadelphia Union",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Barlon Sequeira",
  "country": "CRC",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Alajuelense",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Boubacar Traoré",
  "country": "MLI",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Jeanne d'Arc FC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Branimir Kalaica",
  "country": "CRO",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Dinamo Zagreb",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Bruno Šutalo",
  "country": "CRO",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Hajduk Split",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Byron Castillo",
  "country": "ECU",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Norte América",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Callum McCowatt",
  "country": "NZL",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Western Suburbs",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Christian Ebere",
  "country": "NGA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "ASJ Academy",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Christophe Janssens",
  "country": "BEL",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Club Brugge",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Connor Probert",
  "country": "NZL",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Western Springs",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Constantin Frommann",
  "country": "GER",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "SC Freiburg",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Cristhian Paredes",
  "country": "PAR",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Guarani",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Dane Schnell",
  "country": "NZL",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Western Springs",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Daniel Nesseler",
  "country": "GER",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Bayer Leverkusen",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Daniel Villegas",
  "country": "CRC",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Alajuelense",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Danny Barbir",
  "country": "USA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "West Bromwich Albion",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Darixon Vuelto",
  "country": "ECU",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Victoria",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Darwin Diego",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1999,
  "club_2015": "Vida",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "David Enogela",
  "country": "NGA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Young Stars FC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Davor Lovren",
  "country": "CRO",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Dinamo Zagreb",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Denil Maldonado",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Motagua",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Dennis Geiger",
  "country": "GER",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "1899 Hoffenheim",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Diego González",
  "country": "CHI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "O'Higgins",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Diego Soto",
  "country": "CHI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Universidad de Concepción",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Dominik Franke",
  "country": "GER",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "RB Leipzig",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ejike Ikwu",
  "country": "NGA",
  "position": "DF",
  "birth_year": 1999,
  "club_2015": "Starplus FC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Enes Akyol",
  "country": "GER",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Hertha BSC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Fabián Monilla",
  "country": "CHI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Universidad Católica",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Facundo Pardo",
  "country": "ARG",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Newell's Old Boys",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Federico Vietto",
  "country": "ARG",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Racing Club",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Finn Dahmen",
  "country": "GER",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Mainz 05",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Fodé Camara",
  "country": "GUI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Cefomig",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Franco Petroli",
  "country": "ARG",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "River Plate",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Gabriel Batista",
  "country": "BRA",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Flamengo",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Gaëtan Coucke",
  "country": "BEL",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Genk",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Geovane",
  "country": "BRA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Vitória",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ghaith Sulaiman",
  "country": "PAR",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Tishreen",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Gianluca Mancuso",
  "country": "ARG",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Vélez Sarsfield",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Haji Wright",
  "country": "USA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "New York Cosmos",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Hassan Al-Damen",
  "country": "PAR",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Al-Ittihad",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Hugo Arellano",
  "country": "USA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "LA Galaxy",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ignacio Azúa",
  "country": "CHI",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Universidad de Chile",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ignacio Saavedra",
  "country": "CHI",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Universidad Católica",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ivan Delić",
  "country": "CRO",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Hajduk Split",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ivan Nevistić",
  "country": "CRO",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Rijeka",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Janus Vivar",
  "country": "ECU",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Norte América",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Jean Peña",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "El Nacional",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Jhonner Montezuma",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Norte América",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Joe Gallardo",
  "country": "USA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Monterrey",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Joel Osikel",
  "country": "NGA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Young Eleven FC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Joel Quintero",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Emelec",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "John Nelson",
  "country": "USA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Internationals",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Jorge Morel",
  "country": "PAR",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Libertad",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Josué Colmán",
  "country": "PAR",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Cerro Porteño",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "José Flor",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "El Nacional",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Juan Antonio Di Lorenzo",
  "country": "ARG",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Independiente",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Juan José Soriano",
  "country": "CHI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Universidad Católica",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Juan Miguel Ojeda",
  "country": "PAR",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Sportivo Luqueño",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Juan Nazareno",
  "country": "ECU",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Independiente del Valle",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Jules Keita",
  "country": "GUI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "FC Attouga",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Julián Chicco",
  "country": "ARG",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Boca Juniors",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Kamel Koaeh",
  "country": "PAR",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Al-Shurta",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Karim Conté",
  "country": "GUI",
  "position": "FW",
  "birth_year": 1999,
  "club_2015": "Aspire Academy",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Kevin Minda",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "LDU Quito",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Kevin Silva",
  "country": "USA",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Players Development Academy",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Kim Jung-min",
  "country": "KOR",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Gwangju FC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Kino Delorge",
  "country": "BEL",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Genk",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Laurent Lemoine",
  "country": "BEL",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Club Brugge",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Leodán Chala",
  "country": "ECU",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "El Nacional",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Lincoln",
  "country": "BRA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Grêmio",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Liziero",
  "country": "BRA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "São Paulo",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luca de la Torre",
  "country": "USA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Fulham",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Lucas Ferraz Vila",
  "country": "ARG",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "River Plate",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luis Giménez",
  "country": "PAR",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Olimpia",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luis Olivera",
  "country": "ARG",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "River Plate",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luis Salas",
  "country": "CHI",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Colo-Colo",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luis Ureta",
  "country": "CHI",
  "position": "GK",
  "birth_year": 1999,
  "club_2015": "O'Higgins",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luka Pasariček",
  "country": "CRO",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Dinamo Zagreb",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luke Johnson",
  "country": "NZL",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "North Shore United",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luvuyo Mkatshana",
  "country": "RSA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Bidvest Wits",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Luís Henrique",
  "country": "BRA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Botafogo",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Léo Santos",
  "country": "BRA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Corinthians",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Mamadou Fofana",
  "country": "MLI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Stade Malien",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Mamadou Sangaré",
  "country": "MLI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Cercle Olympique de Bamako",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Mamady Diarra",
  "country": "MLI",
  "position": "FW",
  "birth_year": 2000,
  "club_2015": "Yeelen FC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Manuel Reyes",
  "country": "CHI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Universidad Católica",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Marin Karamarko",
  "country": "CRO",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "OSK Otok",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Marin Šverko",
  "country": "CRO",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Karlsruher SC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Mathías Pinto",
  "country": "CHI",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Universidad de Chile",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Matisse Thuys",
  "country": "BEL",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Genk",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Matko Babić",
  "country": "CRO",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Lokomotiva",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Matthew Olosunde",
  "country": "USA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "New York Red Bulls",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Matthias Verreth",
  "country": "BEL",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "PSV Eindhoven",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Matías Roskopf",
  "country": "ARG",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Boca Juniors",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Meris Skenderović",
  "country": "GER",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "1899 Hoffenheim",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Michael Perelló",
  "country": "ECU",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Platense",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Michael Woud",
  "country": "NZL",
  "position": "GK",
  "birth_year": 1999,
  "club_2015": "Bay Olympic",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Miguel Ajú",
  "country": "CRC",
  "position": "GK",
  "birth_year": 1999,
  "club_2015": "Alajuelense",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Miguel Ángel Martínez",
  "country": "PAR",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "General Díaz",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Mohamed Camara",
  "country": "GUI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Fello Star",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Mohamed Kourouma",
  "country": "GUI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Alde & Action",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Mohammad Al-Hallak",
  "country": "PAR",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Al-Kiswah",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Mohammad Khoja",
  "country": "PAR",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Jableh",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Mondli Mpoto",
  "country": "RSA",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "SuperSport United",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Moussa Diakité",
  "country": "MLI",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "ASKO",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Omar Kadije",
  "country": "PAR",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Hutteen",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Orel Mangala",
  "country": "BEL",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Anderlecht",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Orji Okwonkwo",
  "country": "NGA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Abuja",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Ousmane Camara",
  "country": "GUI",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "FC Attouga",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Ousmane Diakité",
  "country": "MLI",
  "position": "FW",
  "birth_year": 2000,
  "club_2015": "Yeelen FC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Owen Parker-Price",
  "country": "NZL",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Western Suburbs",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Patrick Sequeira",
  "country": "CRC",
  "position": "GK",
  "birth_year": 1999,
  "club_2015": "Limón",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Pierre da Silva",
  "country": "USA",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Orlando City",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Reeve Frosler",
  "country": "RSA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Bidvest Wits",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Renny Jaramillo",
  "country": "ECU",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Independiente del Valle",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Riyaaz Ismail",
  "country": "RSA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Hellenic",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Roberto Córdoba",
  "country": "CRC",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "San Carlos",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Rodi Ferreira",
  "country": "PAR",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Olimpia",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Rubin Seigers",
  "country": "BEL",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Genk",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Samuel Diarra",
  "country": "MLI",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "ASKO",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Sanele Tshabalala",
  "country": "RSA",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Bidvest Wits",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Sergio Díaz",
  "country": "PAR",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Cerro Porteño",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Siaka Bagayoko",
  "country": "MLI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Djoliba AC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Sibongakonke Mbatha",
  "country": "RSA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "School of Exellence",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Simón Ramírez",
  "country": "CHI",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Huachipato",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "r16",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Sphephelo Sithole",
  "country": "RSA",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Kwazulu Natal Academy",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Steve Ryckaert",
  "country": "BEL",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Gent",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Sunday Alimi",
  "country": "NGA",
  "position": "FW",
  "birth_year": 1999,
  "club_2015": "Topworld FC",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "final",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Tanner Dieterich",
  "country": "USA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Real Salt Lake",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Tebogo Qinisile",
  "country": "RSA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Bloemfontein Celtic",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Terry Osei-Berkoe",
  "country": "BEL",
  "position": "FW",
  "birth_year": 1998,
  "club_2015": "Club Brugge",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Tommy McCabe",
  "country": "USA",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Players Development Academy",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Vinko Soldo",
  "country": "CRO",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Dinamo Zagreb",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Walter Kubheka",
  "country": "RSA",
  "position": "GK",
  "birth_year": 1999,
  "club_2015": "Mamelodi Sundowns",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Wesly Decas",
  "country": "ECU",
  "position": "DF",
  "birth_year": 1999,
  "club_2015": "Pumas",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Will Pulisic",
  "country": "USA",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Richmond United",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "William Ghannam",
  "country": "PAR",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Al-Majd",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Wisdom Quaye",
  "country": "ECU",
  "position": "MF",
  "birth_year": 1998,
  "club_2015": "Vida",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Wiseman Meyiwa",
  "country": "RSA",
  "position": "MF",
  "birth_year": 1999,
  "club_2015": "Kaizer Chiefs",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Wout Faes",
  "country": "BEL",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Anderlecht",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "sf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Zé Marcos",
  "country": "BRA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "Atlético Paranaense",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 },
 {
  "name": "Éder Militão",
  "country": "BRA",
  "position": "DF",
  "birth_year": 1998,
  "club_2015": "São Paulo",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "qf",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": True
 },
 {
  "name": "Óscar Benítez",
  "country": "PAR",
  "position": "GK",
  "birth_year": 1998,
  "club_2015": "Rubio Ñu",
  "goals_u17wc_2015": 0,
  "team_stage_2015": "group",
  "market_aware_2015": False,
  "segment": "baseline",
  "p_reach": 0.11,
  "fact_points": 0,
  "projection_points": 220,
  "mpi": 7720,
  "outcome_reached_eur5m_peak": False
 }
]
